targets:
  $default:
    builders:
      drift_dev:
        enabled: true
        options:
          skip_verification_code: false
          use_data_class_name_for_companions: true
          use_column_name_as_json_key_when_defined_in_moor_file: true
          generate_connect_constructor: true
      riverpod_generator:
        enabled: true
      json_serializable:
        enabled: true
